apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  selector:
    matchLabels:
      run: poi
  replicas: 2
  template:
    metadata:
      labels:
        run: poi
    spec:
      containers:
      - name: poi
        image: registrykco9435.azurecr.io/tripinsights/poi:v1
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlsecret # the name of the Kubernetes secret containing the data
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsecret # the name of the Kubernetes secret containing the data
              key: SQL_PASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlsecret # the name of the Kubernetes secret containing the data
              key: SQL_SERVER
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqlsecret # the name of the Kubernetes secret containing the data
              key: SQL_DBNAME
        ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    run: poi
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: poi